In [3]:
print('seggs')

seggs


In [1]:
import numpy as np

In [5]:
import pandas as pd

In [3]:
testArray = np.array([1,2,3,4,5,6,7,8,9,10])

In [4]:
testArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.random.randint(100)

21

In [9]:
bigArray = np.arange(0,100)

In [10]:
bigArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
bigArray[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
bigArray = bigArray.reshape(10,10)

In [24]:
bigArray

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [31]:
bigArray[0][0:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])